#define GPIOPortA_AHB_base_addr     0x40058000
#define GPIOPortB_AHB_base_addr     0x40059000
#define GPIOPortC_AHB_base_addr     0x4005A000
#define GPIOPortD_AHB_base_addr     0x4005B000
#define GPIOPortE_AHB_base_addr     0x4005C000
#define GPIOPortF_AHB_base_addr     0x4005D000

#define GPIODATA_A      *((volatile u32*)(0x400583FC))
#define GPIODATA_B      *((volatile u32*)(0x400593FC))
#define GPIODATA_C      *((volatile u32*)(0x4005A3FC))
#define GPIODATA_D      *((volatile u32*)(0x4005B3FC))
#define GPIODATA_E      *((volatile u32*)(0x4005C3FC))
#define GPIODATA_F      *((volatile u32*)(0x4005D3FC))
	

#define GPIO_portA_GPIODIR      *((volatile u32*)(GPIOPortA_AHB_base_addr+0x400))
#define GPIO_portA_GPIOAFSEL    *((volatile u32*)(GPIOPortA_AHB_base_addr+0x420))
#define GPIO_portA_GPIODR2R     *((volatile u32*)(GPIOPortA_AHB_base_addr+0x500))
#define GPIO_portA_GPIODR4R     *((volatile u32*)(GPIOPortA_AHB_base_addr+0x504))
#define GPIO_portA_GPIODR8R     *((volatile u32*)(GPIOPortA_AHB_base_addr+0x508))
#define GPIO_portA_GPIOODR      *((volatile u32*)(GPIOPortA_AHB_base_addr+0x50C))
#define GPIO_portA_GPIOPUR      *((volatile u32*)(GPIOPortA_AHB_base_addr+0x510))
#define GPIO_portA_GPIOPDR      *((volatile u32*)(GPIOPortA_AHB_base_addr+0x514))
#define GPIO_portA_GPIODEN      *((volatile u32*)(GPIOPortA_AHB_base_addr+0x51C))
#define GPIO_portA_GPIOLOCK     *((volatile u32*)(GPIOPortA_AHB_base_addr+0x520))
#define GPIO_portA_GPIOCR       *((volatile u32*)(GPIOPortA_AHB_base_addr+0x524))
#define GPIO_portA_GPIOAMSEL    *((volatile u32*)(GPIOPortA_AHB_base_addr+0x528))
#define GPIO_portA_GPIOPCTL     *((volatile u32*)(GPIOPortA_AHB_base_addr+0x52C))
#define GPIO_portA_GPIOADCCTL   *((volatile u32*)(GPIOPortA_AHB_base_addr+0x530))


#define GPIO_portB_GPIODIR      *((volatile u32*)(GPIOPortB_AHB_base_addr+0x400))
#define GPIO_portB_GPIOAFSEL    *((volatile u32*)(GPIOPortB_AHB_base_addr+0x420))
#define GPIO_portB_GPIODR2R     *((volatile u32*)(GPIOPortB_AHB_base_addr+0x500))
#define GPIO_portB_GPIODR4R     *((volatile u32*)(GPIOPortB_AHB_base_addr+0x504))
#define GPIO_portB_GPIODR8R     *((volatile u32*)(GPIOPortB_AHB_base_addr+0x508))
#define GPIO_portB_GPIOODR      *((volatile u32*)(GPIOPortB_AHB_base_addr+0x50C))
#define GPIO_portB_GPIOPUR      *((volatile u32*)(GPIOPortB_AHB_base_addr+0x510))
#define GPIO_portB_GPIOPDR      *((volatile u32*)(GPIOPortB_AHB_base_addr+0x514))
#define GPIO_portB_GPIODEN      *((volatile u32*)(GPIOPortB_AHB_base_addr+0x51C))
#define GPIO_portB_GPIOLOCK     *((volatile u32*)(GPIOPortB_AHB_base_addr+0x520))
#define GPIO_portB_GPIOCR       *((volatile u32*)(GPIOPortB_AHB_base_addr+0x524))
#define GPIO_portB_GPIOAMSEL    *((volatile u32*)(GPIOPortB_AHB_base_addr+0x528))
#define GPIO_portB_GPIOPCTL     *((volatile u32*)(GPIOPortB_AHB_base_addr+0x52C))
#define GPIO_portB_GPIOADCCTL   *((volatile u32*)(GPIOPortB_AHB_base_addr+0x530))


#define GPIO_portC_GPIODIR      *((volatile u32*)(GPIOPortC_AHB_base_addr+0x400))
#define GPIO_portC_GPIOAFSEL    *((volatile u32*)(GPIOPortC_AHB_base_addr+0x420))
#define GPIO_portC_GPIODR2R     *((volatile u32*)(GPIOPortC_AHB_base_addr+0x500))
#define GPIO_portC_GPIODR4R     *((volatile u32*)(GPIOPortC_AHB_base_addr+0x504))
#define GPIO_portC_GPIODR8R     *((volatile u32*)(GPIOPortC_AHB_base_addr+0x508))
#define GPIO_portC_GPIOODR      *((volatile u32*)(GPIOPortC_AHB_base_addr+0x50C))
#define GPIO_portC_GPIOPUR      *((volatile u32*)(GPIOPortC_AHB_base_addr+0x510))
#define GPIO_portC_GPIOPDR      *((volatile u32*)(GPIOPortC_AHB_base_addr+0x514))
#define GPIO_portC_GPIODEN      *((volatile u32*)(GPIOPortC_AHB_base_addr+0x51C))
#define GPIO_portC_GPIOLOCK     *((volatile u32*)(GPIOPortC_AHB_base_addr+0x520))
#define GPIO_portC_GPIOCR       *((volatile u32*)(GPIOPortC_AHB_base_addr+0x524))
#define GPIO_portC_GPIOAMSEL    *((volatile u32*)(GPIOPortC_AHB_base_addr+0x528))
#define GPIO_portC_GPIOPCTL     *((volatile u32*)(GPIOPortC_AHB_base_addr+0x52C))
#define GPIO_portC_GPIOADCCTL   *((volatile u32*)(GPIOPortC_AHB_base_addr+0x530))


#define GPIO_portD_GPIODIR      *((volatile u32*)(GPIOPortD_AHB_base_addr+0x400))
#define GPIO_portD_GPIOAFSEL    *((volatile u32*)(GPIOPortD_AHB_base_addr+0x420))
#define GPIO_portD_GPIODR2R     *((volatile u32*)(GPIOPortD_AHB_base_addr+0x500))
#define GPIO_portD_GPIODR4R     *((volatile u32*)(GPIOPortD_AHB_base_addr+0x504))
#define GPIO_portD_GPIODR8R     *((volatile u32*)(GPIOPortD_AHB_base_addr+0x508))
#define GPIO_portD_GPIOODR      *((volatile u32*)(GPIOPortD_AHB_base_addr+0x50C))
#define GPIO_portD_GPIOPUR      *((volatile u32*)(GPIOPortD_AHB_base_addr+0x510))
#define GPIO_portD_GPIOPDR      *((volatile u32*)(GPIOPortD_AHB_base_addr+0x514))
#define GPIO_portD_GPIODEN      *((volatile u32*)(GPIOPortD_AHB_base_addr+0x51C))
#define GPIO_portD_GPIOLOCK     *((volatile u32*)(GPIOPortD_AHB_base_addr+0x520))
#define GPIO_portD_GPIOCR       *((volatile u32*)(GPIOPortD_AHB_base_addr+0x524))
#define GPIO_portD_GPIOAMSEL    *((volatile u32*)(GPIOPortD_AHB_base_addr+0x528))
#define GPIO_portD_GPIOPCTL     *((volatile u32*)(GPIOPortD_AHB_base_addr+0x52C))
#define GPIO_portD_GPIOADCCTL   *((volatile u32*)(GPIOPortD_AHB_base_addr+0x530))


#define GPIO_portE_GPIODIR      *((volatile u32*)(GPIOPortD_AHB_base_addr+0x400))
#define GPIO_portE_GPIOAFSEL    *((volatile u32*)(GPIOPortD_AHB_base_addr+0x420))
#define GPIO_portE_GPIODR2R     *((volatile u32*)(GPIOPortD_AHB_base_addr+0x500))
#define GPIO_portE_GPIODR4R     *((volatile u32*)(GPIOPortD_AHB_base_addr+0x504))
#define GPIO_portE_GPIODR8R     *((volatile u32*)(GPIOPortD_AHB_base_addr+0x508))
#define GPIO_portE_GPIOODR      *((volatile u32*)(GPIOPortD_AHB_base_addr+0x50C))
#define GPIO_portE_GPIOPUR      *((volatile u32*)(GPIOPortD_AHB_base_addr+0x510))
#define GPIO_portE_GPIOPDR      *((volatile u32*)(GPIOPortD_AHB_base_addr+0x514))
#define GPIO_portE_GPIODEN      *((volatile u32*)(GPIOPortD_AHB_base_addr+0x51C))
#define GPIO_portE_GPIOLOCK     *((volatile u32*)(GPIOPortD_AHB_base_addr+0x520))
#define GPIO_portE_GPIOCR       *((volatile u32*)(GPIOPortD_AHB_base_addr+0x524))
#define GPIO_portE_GPIOAMSEL    *((volatile u32*)(GPIOPortD_AHB_base_addr+0x528))
#define GPIO_portE_GPIOPCTL     *((volatile u32*)(GPIOPortD_AHB_base_addr+0x52C))
#define GPIO_portE_GPIOADCCTL   *((volatile u32*)(GPIOPortD_AHB_base_addr+0x530))


#define GPIO_portF_GPIODIR      *((volatile u32*)(GPIOPortD_AHB_base_addr+0x400))
#define GPIO_portF_GPIOAFSEL    *((volatile u32*)(GPIOPortD_AHB_base_addr+0x420))
#define GPIO_portF_GPIODR2R     *((volatile u32*)(GPIOPortD_AHB_base_addr+0x500))
#define GPIO_portF_GPIODR4R     *((volatile u32*)(GPIOPortD_AHB_base_addr+0x504))
#define GPIO_portF_GPIODR8R     *((volatile u32*)(GPIOPortD_AHB_base_addr+0x508))
#define GPIO_portF_GPIOODR      *((volatile u32*)(GPIOPortD_AHB_base_addr+0x50C))
#define GPIO_portF_GPIOPUR      *((volatile u32*)(GPIOPortD_AHB_base_addr+0x510))
#define GPIO_portF_GPIOPDR      *((volatile u32*)(GPIOPortD_AHB_base_addr+0x514))
#define GPIO_portF_GPIODEN      *((volatile u32*)(GPIOPortD_AHB_base_addr+0x51C))
#define GPIO_portF_GPIOLOCK     *((volatile u32*)(GPIOPortD_AHB_base_addr+0x520))
#define GPIO_portF_GPIOCR       *((volatile u32*)(GPIOPortD_AHB_base_addr+0x524))
#define GPIO_portF_GPIOAMSEL    *((volatile u32*)(GPIOPortD_AHB_base_addr+0x528))
#define GPIO_portF_GPIOPCTL     *((volatile u32*)(GPIOPortD_AHB_base_addr+0x52C))
#define GPIO_portF_GPIOADCCTL   *((volatile u32*)(GPIOPortD_AHB_base_addr+0x530))