#ifndef NVIC_CONFIG_H_
#define NVIC_CONFIG_H_


#define	GPIO_Port_A_State	enable
#define	GPIO_Port_B_State	enable
#define	GPIO_Port_C_State	enable
#define	GPIO_Port_D_State	enable
#define	GPIO_Port_E_State	enable
#define	UART0_State	enable
#define	UART1_State	enable
#define	SSI0_State	enable
#define	I2C0_State	enable
#define	PWM0_Fault_State	disable
#define	PWM0_Generator_0_State	disable
#define	PWM0_Generator_1_State	disable
#define	PWM0_Generator_2_State	disable
#define	QEI0_State	disable
#define	ADC0_Sequence_0_State	disable
#define	ADC0_Sequence_1_State	disable
#define	ADC0_Sequence_2_State	disable
#define	ADC0_Sequence_3_State	disable
#define	Watchdog_Timers_0_and_1_State	disable
#define	Bit_Timer_16_32_0A_State	enable
#define	Bit_Timer_16_32_0B_State	enable
#define	Bit_Timer_16_32_1A_State	enable
#define	Bit_Timer_16_32_1B_State	enable
#define	Bit_Timer_16_32_2A_State	enable
#define	Bit_Timer_16_32_2B_State	enable
#define	Analog_Comparator_0_State	enable
#define	Analog_Comparator_1_State	disable
#define	System_Control_State	disable
#define	Flash_Memory_Control_and_EEPROM_Control_State	disable
#define	GPIO_Port_F_State	enable
#define	UART2_State	disable
#define	SSI1_State	disable
#define	Bit_Timer_16_32_3A_State	disable
#define	Bit_Timer_16_32_3B_State	disable
#define	I2C1_State	disable
#define	QEI1_State	disable
#define	CAN0_State	disable
#define	CAN1_State	disable
#define	Hibernation_Module_State	disable
#define	USB_State	disable
#define	PWM_Generator_3_State	disable
#define	UDMA_Software_State	disable
#define	UDMA_Error_State	disable
#define	ADC1_Sequence_0_State	disable
#define	ADC1_Sequence_1_State	disable
#define	ADC1_Sequence_2_State	disable
#define	ADC1_Sequence_3_State	disable
#define	SSI2_State	disable
#define	SSI3_State	disable
#define	UART3_State	disable
#define	UART4_State	disable
#define	UART5_State	disable
#define	UART6_State	disable
#define	UART7_State	disable
#define	I2C2_State	disable
#define	I2C3_State	disable
#define	Bit_Timer_16_32_4A_State	disable
#define	Bit_Timer_16_32_4B_State	disable
#define	Bit_Timer_16_32_5A_State	disable
#define	Bit_Timer_16_32_5B_State	disable
#define	Bit_Timer_32_64_0A_State	disable
#define	Bit_Timer_32_64_0B_State	disable
#define	Bit_Timer_32_64_1A_State	disable
#define	Bit_Timer_32_64_1B_State	disable
#define	Bit_Timer_32_64_2A_State	disable
#define	Bit_Timer_32_64_2B_State	disable
#define	Bit_Timer_32_64_3A_State	disable
#define	Bit_Timer_32_64_3B_State	disable
#define	Bit_Timer_32_64_4A_State	disable
#define	Bit_Timer_32_64_4B_State	disable
#define	Bit_Timer_32_64_5A_State	disable
#define	Bit_Timer_32_64_5B_State	disable
#define	System_Exception_imprecise_State	enable
#define	PWM1_Generator_0_State	disable
#define	PWM1_Generator_1_State	disable
#define	PWM1_Generator_2_State	disable
#define	PWM1_Generator_3_State	disable
#define	PWM1_Fault_State	disable





#define	GPIO_Port_A_Pri	priority_0
#define	GPIO_Port_B_Pri	priority_1
#define	GPIO_Port_C_Pri	priority_2
#define	GPIO_Port_D_Pri	priority_3
#define	GPIO_Port_E_Pri	priority_0
#define	UART0_Pri	priority_1
#define	UART1_Pri	priority_2
#define	SSI0_Pri	priority_3
#define	I2C0_Pri	priority_0
#define	PWM0_Fault_Pri	priority_1
#define	PWM0_Generator_0_Pri	priority_2
#define	PWM0_Generator_1_Pri	priority_3
#define	PWM0_Generator_2_Pri	priority_0
#define	QEI0_Pri	priority_1
#define	ADC0_Sequence_0_Pri	priority_2
#define	ADC0_Sequence_1_Pri	priority_3
#define	ADC0_Sequence_2_Pri	priority_0
#define	ADC0_Sequence_3_Pri	priority_1
#define	Watchdog_Timers_0_and_1_Pri	priority_2
#define	Bit_Timer_16_32_0A_Pri	priority_3
#define	Bit_Timer_16_32_0B_Pri	priority_0
#define	Bit_Timer_16_32_1A_Pri	priority_1
#define	Bit_Timer_16_32_1B_Pri	priority_2
#define	Bit_Timer_16_32_2A_Pri	priority_3
#define	Bit_Timer_16_32_2B_Pri	priority_0
#define	Analog_Comparator_0_Pri	priority_1
#define	Analog_Comparator_1_Pri	priority_2
#define	Reserved_Pri	priority_3
#define	System_Control_Pri	priority_0
#define	Flash_Memory_Control_and_EEPROM_Control_Pri	priority_1
#define	GPIO_Port_F_Pri	priority_2
#define	UART2_Pri	priority_1
#define	SSI1_Pri	priority_2
#define	Bit_Timer_16_32_3A_Pri	priority_3
#define	Bit_Timer_16_32_3B_Pri	priority_0
#define	I2C1_Pri	priority_1
#define	QEI1_Pri	priority_2
#define	CAN0_Pri	priority_3
#define	CAN1_Pri	priority_0

#define	Hibernation_Module_Pri	priority_3
#define	USB_Pri	priority_0
#define	PWM_Generator_3_Pri	priority_1
#define	UDMA_Software_Pri	priority_2
#define	UDMA_Error_Pri	priority_3
#define	ADC1_Sequence_0_Pri	priority_0
#define	ADC1_Sequence_1_Pri	priority_1
#define	ADC1_Sequence_2_Pri	priority_2
#define	ADC1_Sequence_3_Pri	priority_3

#define	SSI2_Pri	priority_1
#define	SSI3_Pri	priority_2
#define	UART3_Pri	priority_3
#define	UART4_Pri	priority_0
#define	UART5_Pri	priority_1
#define	UART6_Pri	priority_2
#define	UART7_Pri	priority_3
#define	I2C2_Pri	priority_0
#define	I2C3_Pri	priority_1
#define	Bit_Timer_16_32_4A_Pri	priority_2
#define	Bit_Timer_16_32_4B_Pri	priority_3

#define	Bit_Timer_16_32_5A_Pri	priority_0
#define	Bit_Timer_16_32_5B_Pri	priority_1
#define	Bit_Timer_32_64_0A_Pri	priority_2
#define	Bit_Timer_32_64_0B_Pri	priority_3
#define	Bit_Timer_32_64_1A_Pri	priority_0
#define	Bit_Timer_32_64_1B_Pri	priority_1
#define	Bit_Timer_32_64_2A_Pri	priority_2
#define	Bit_Timer_32_64_2B_Pri	priority_3
#define	Bit_Timer_32_64_3A_Pri	priority_0
#define	Bit_Timer_32_64_3B_Pri	priority_1
#define	Bit_Timer_32_64_4A_Pri	priority_2
#define	Bit_Timer_32_64_4B_Pri	priority_3
#define	Bit_Timer_32_64_5A_Pri	priority_0
#define	Bit_Timer_32_64_5B_Pri	priority_1
#define	System_Exception_imprecise_Pri	priority_2
#define	PWM1_Generator_0_Pri	priority_2
#define	PWM1_Generator_1_Pri	priority_3
#define	PWM1_Generator_2_Pri	priority_0
#define	PWM1_Generator_3_Pri	priority_1
#define	PWM1_Fault_Pri	priority_2

#endif  /*NVIC_CONFIG_H_*/

